"""Three archived communities from Unit 3.

1. Civic mobilisation — political movement, early / mid / late.
2. Research collaborations — scientific co-authorship, initial / archived / evolved.
3. Health rumour — misinformation cascade, early / growth / intervention.
"""

from __future__ import annotations

COLLECTIONS: list[dict] = [
    {
        "id": "political",
        "accession": "POL-2019-0041",
        "title": "Civic mobilisation",
        "kicker": "Online political movement",
        "summary": "Two ward forums start apart, grow a single cross-link, then fuse into one campaign graph. Comments are the archived thread underneath the network.",
        "palette": ["#b4331a", "#2c4a3e"],
        "slices": [
            {
                "id": "early",
                "label": "Early",
                "when": "Jan 2019",
                "note": "Two separate communities. North ward and south ward do not yet share a thread.",
                "nodes": [
                    {"id": "mina", "name": "Mina Voss", "role": "North organiser"},
                    {"id": "rafael", "name": "Rafael Ortiz", "role": "Labour thread"},
                    {"id": "helen", "name": "Helen Cho", "role": "Student union"},
                    {"id": "yusuf", "name": "Yusuf Demir", "role": "Neighbourhood page"},
                    {"id": "priya", "name": "Priya Nair", "role": "South ward forum"},
                    {"id": "lukas", "name": "Lukas Meier", "role": "City blog"},
                    {"id": "amira", "name": "Amira Haddad", "role": "Diaspora group"},
                ],
                "edges": [
                    ["mina", "rafael", 2, "reply"],
                    ["mina", "helen", 2, "reply"],
                    ["mina", "yusuf", 2, "reply"],
                    ["rafael", "helen", 2, "reply"],
                    ["rafael", "yusuf", 2, "reply"],
                    ["helen", "yusuf", 2, "reply"],
                    ["priya", "lukas", 2, "reply"],
                    ["priya", "amira", 2, "reply"],
                    ["lukas", "amira", 2, "reply"],
                ],
                "comments": [
                    {"author": "mina", "lang": "en", "text": "The January deposit shows our ward still talking only to itself. Can we post the timetable before the rally?"},
                    {"author": "helen", "lang": "en", "text": "Student union minutes are in the repository. I disagree with the slogan, but the turnout numbers are useful."},
                    {"author": "priya", "lang": "en", "text": "South forum is drafting its own leaflet. Thanks for keeping the archive copy."},
                    {"author": "lukas", "lang": "de", "text": "Die Gemeinschaften sind im Archiv noch getrennt."},
                    {"author": "rafael", "lang": "en", "text": "Shut up, you dumb loser. North ward does not need another speech."},
                ],
            },
            {
                "id": "mid",
                "label": "Mid",
                "when": "Mar 2019",
                "note": "A journalist joins the south forum and one cross-link appears between Helen and Priya. The groups are still distinct.",
                "nodes": [
                    {"id": "mina", "name": "Mina Voss", "role": "North organiser"},
                    {"id": "rafael", "name": "Rafael Ortiz", "role": "Labour thread"},
                    {"id": "helen", "name": "Helen Cho", "role": "Student union"},
                    {"id": "yusuf", "name": "Yusuf Demir", "role": "Neighbourhood page"},
                    {"id": "priya", "name": "Priya Nair", "role": "South ward forum"},
                    {"id": "lukas", "name": "Lukas Meier", "role": "City blog"},
                    {"id": "amira", "name": "Amira Haddad", "role": "Diaspora group"},
                    {"id": "jonah", "name": "Jonah Ellis", "role": "City reporter"},
                ],
                "edges": [
                    ["mina", "rafael", 2, "reply"],
                    ["mina", "helen", 2, "reply"],
                    ["mina", "yusuf", 2, "reply"],
                    ["rafael", "helen", 2, "reply"],
                    ["rafael", "yusuf", 2, "reply"],
                    ["helen", "yusuf", 2, "reply"],
                    ["priya", "lukas", 2, "reply"],
                    ["priya", "amira", 2, "reply"],
                    ["lukas", "amira", 2, "reply"],
                    ["priya", "jonah", 2, "reply"],
                    ["lukas", "jonah", 1, "reply"],
                    ["helen", "priya", 1, "bridge"],
                ],
                "comments": [
                    {"author": "helen", "lang": "en", "text": "Cross-posting increased, yet the two groups are still distinct. I shared our leaflet in the south thread."},
                    {"author": "jonah", "lang": "en", "text": "I am filing the March snapshot. The only new bridge is Helen to Priya."},
                    {"author": "priya", "lang": "es", "text": "Gracias por el enlace al archivo de marzo."},
                    {"author": "amira", "lang": "en", "text": "Your kind is not welcome in this movement."},
                    {"author": "yusuf", "lang": "en", "text": "Neighbourhood reports are more reliable than the anonymous post."},
                ],
            },
            {
                "id": "late",
                "label": "Late",
                "when": "Jun 2019",
                "note": "Cross-links now outnumber the old ward boundaries. Louvain reads the two forums as one campaign.",
                "nodes": [
                    {"id": "mina", "name": "Mina Voss", "role": "North organiser"},
                    {"id": "rafael", "name": "Rafael Ortiz", "role": "Labour thread"},
                    {"id": "helen", "name": "Helen Cho", "role": "Student union"},
                    {"id": "yusuf", "name": "Yusuf Demir", "role": "Neighbourhood page"},
                    {"id": "priya", "name": "Priya Nair", "role": "South ward forum"},
                    {"id": "lukas", "name": "Lukas Meier", "role": "City blog"},
                    {"id": "amira", "name": "Amira Haddad", "role": "Diaspora group"},
                    {"id": "jonah", "name": "Jonah Ellis", "role": "City reporter"},
                ],
                "edges": [
                    ["mina", "rafael", 1, "reply"],
                    ["mina", "helen", 1, "reply"],
                    ["mina", "yusuf", 1, "reply"],
                    ["rafael", "helen", 1, "reply"],
                    ["rafael", "yusuf", 1, "reply"],
                    ["helen", "yusuf", 1, "reply"],
                    ["priya", "lukas", 1, "reply"],
                    ["priya", "amira", 1, "reply"],
                    ["priya", "jonah", 1, "reply"],
                    ["lukas", "amira", 1, "reply"],
                    ["lukas", "jonah", 1, "reply"],
                    ["amira", "jonah", 1, "reply"],
                    ["mina", "priya", 2, "bridge"],
                    ["mina", "lukas", 2, "bridge"],
                    ["mina", "amira", 2, "bridge"],
                    ["mina", "jonah", 2, "bridge"],
                    ["rafael", "priya", 2, "bridge"],
                    ["rafael", "lukas", 2, "bridge"],
                    ["rafael", "amira", 2, "bridge"],
                    ["rafael", "jonah", 2, "bridge"],
                    ["helen", "priya", 2, "bridge"],
                    ["helen", "lukas", 2, "bridge"],
                    ["helen", "amira", 2, "bridge"],
                    ["helen", "jonah", 2, "bridge"],
                    ["yusuf", "priya", 2, "bridge"],
                    ["yusuf", "lukas", 2, "bridge"],
                    ["yusuf", "amira", 2, "bridge"],
                    ["yusuf", "jonah", 2, "bridge"],
                ],
                "comments": [
                    {"author": "jonah", "lang": "en", "text": "Late snapshot: multiple cross-links. The two forums now move as one campaign."},
                    {"author": "mina", "lang": "en", "text": "Both wards are sharing the same rally thread. Please keep the primary source attached."},
                    {"author": "rafael", "lang": "en", "text": "You are a clown and everyone in the south forum knows it."},
                    {"author": "lukas", "lang": "de", "text": "Halt die Fresse, du Idiot."},
                    {"author": "amira", "lang": "en", "text": "I think the communities merged once the hashtags overlapped. Let's keep the record civil."},
                ],
            },
        ],
    },
    {
        "id": "science",
        "accession": "SCI-2018-1187",
        "title": "Research collaborations",
        "kicker": "Scientific co-authorship",
        "summary": "A collaboration graph is deposited, then opened again after new joint papers appear. Nodes are researchers. Edges are co-authorship.",
        "palette": ["#8a6a32", "#1f4e79"],
        "slices": [
            {
                "id": "initial",
                "label": "Initial",
                "when": "2018",
                "note": "Two labs. Chen's group and Okonkwo's group share only a single joint paper.",
                "nodes": [
                    {"id": "alice", "name": "Alice Chen", "role": "Natural language processing"},
                    {"id": "bob", "name": "Bob Iyer", "role": "Graph mining"},
                    {"id": "carol", "name": "Carol Santos", "role": "Web archives"},
                    {"id": "dave", "name": "Dave Okonkwo", "role": "Sociology"},
                    {"id": "eve", "name": "Eve Berg", "role": "Public health"},
                ],
                "edges": [
                    ["alice", "bob", 2, "coauthor"],
                    ["alice", "carol", 2, "coauthor"],
                    ["bob", "carol", 2, "coauthor"],
                    ["dave", "eve", 2, "coauthor"],
                    ["bob", "dave", 1, "coauthor"],
                ],
                "comments": [
                    {"author": "alice", "lang": "en", "text": "Thanks for posting the co-authorship list from the archive."},
                    {"author": "carol", "lang": "en", "text": "Can someone check this citation against the library copy? Link rot is already a problem."},
                    {"author": "dave", "lang": "en", "text": "Our sociology notes treat the two labs as separate groups in 2018."},
                    {"author": "bob", "lang": "en", "text": "The bridge between the labs is one joint paper. I would like to hear the other forum too."},
                ],
            },
            {
                "id": "archived",
                "label": "Archived",
                "when": "2019 deposit",
                "note": "The 2018 graph is saved into the scientific archive. Structure is unchanged.",
                "nodes": [
                    {"id": "alice", "name": "Alice Chen", "role": "Natural language processing"},
                    {"id": "bob", "name": "Bob Iyer", "role": "Graph mining"},
                    {"id": "carol", "name": "Carol Santos", "role": "Web archives"},
                    {"id": "dave", "name": "Dave Okonkwo", "role": "Sociology"},
                    {"id": "eve", "name": "Eve Berg", "role": "Public health"},
                ],
                "edges": [
                    ["alice", "bob", 2, "coauthor"],
                    ["alice", "carol", 2, "coauthor"],
                    ["bob", "carol", 2, "coauthor"],
                    ["dave", "eve", 2, "coauthor"],
                    ["bob", "dave", 1, "coauthor"],
                ],
                "comments": [
                    {"author": "carol", "lang": "en", "text": "The archive deposit for this year is complete. This state is the historical reference."},
                    {"author": "eve", "lang": "en", "text": "Eve's public-health notes help explain why the second lab stayed small."},
                    {"author": "alice", "lang": "fr", "text": "Merci, le dépôt de cette année est complet."},
                    {"author": "dave", "lang": "en", "text": "You are an imbecile and a bastard. Stay out of this lab thread."},
                ],
            },
            {
                "id": "evolved",
                "label": "Evolved",
                "when": "2021",
                "note": "New co-authorships tie the two labs into one collaboration community.",
                "nodes": [
                    {"id": "alice", "name": "Alice Chen", "role": "Natural language processing"},
                    {"id": "bob", "name": "Bob Iyer", "role": "Graph mining"},
                    {"id": "carol", "name": "Carol Santos", "role": "Web archives"},
                    {"id": "dave", "name": "Dave Okonkwo", "role": "Sociology"},
                    {"id": "eve", "name": "Eve Berg", "role": "Public health"},
                ],
                "edges": [
                    ["alice", "bob", 2, "coauthor"],
                    ["alice", "carol", 2, "coauthor"],
                    ["alice", "dave", 2, "coauthor"],
                    ["alice", "eve", 2, "coauthor"],
                    ["bob", "carol", 2, "coauthor"],
                    ["bob", "dave", 2, "coauthor"],
                    ["bob", "eve", 2, "coauthor"],
                    ["carol", "dave", 2, "coauthor"],
                    ["carol", "eve", 2, "coauthor"],
                    ["dave", "eve", 2, "coauthor"],
                ],
                "comments": [
                    {"author": "bob", "lang": "en", "text": "Bob and Carol started a joint project on diffusion networks. Alice and Eve co-authored the follow-up."},
                    {"author": "carol", "lang": "en", "text": "Carol's note on link rot belongs in the methods section. The co-authors list grew after the 2021 workshop."},
                    {"author": "eve", "lang": "en", "text": "Let's compare modularity before and after the new papers."},
                    {"author": "alice", "lang": "pt", "text": "O arquivo mostra dois grupos no início."},
                ],
            },
        ],
    },
    {
        "id": "rumour",
        "accession": "RUM-2020-0772",
        "title": "Health rumour cascade",
        "kicker": "Fake news evolution",
        "summary": "A source account seeds a health rumour. Reshares widen the cascade. Fact-checking then cuts the propagation edges, the intervention stage from the slides.",
        "palette": ["#6b2d5b", "#9a3412"],
        "slices": [
            {
                "id": "early",
                "label": "Early",
                "when": "Day 0",
                "note": "The source and two early sharers. The rumour is local.",
                "nodes": [
                    {"id": "pulse", "name": "DailyPulse", "role": "Source account"},
                    {"id": "anita", "name": "Anita Roy", "role": "Early sharer"},
                    {"id": "ben", "name": "Ben Adler", "role": "Early sharer"},
                ],
                "edges": [
                    ["pulse", "anita", 2, "reshare"],
                    ["pulse", "ben", 2, "reshare"],
                    ["anita", "ben", 1, "reshare"],
                ],
                "comments": [
                    {"author": "pulse", "lang": "en", "text": "Share this before the morning edition. The hospitals are hiding the numbers."},
                    {"author": "anita", "lang": "en", "text": "Passing it on. I have not checked a primary source yet."},
                    {"author": "ben", "lang": "en", "text": "You moron, you ruined the whole discussion if you question this."},
                ],
            },
            {
                "id": "growth",
                "label": "Growth",
                "when": "Day 2",
                "note": "The source cluster grows by one account, and a second community is born in the outer ring of reshares.",
                "nodes": [
                    {"id": "pulse", "name": "DailyPulse", "role": "Source account"},
                    {"id": "anita", "name": "Anita Roy", "role": "Early sharer"},
                    {"id": "ben", "name": "Ben Adler", "role": "Early sharer"},
                    {"id": "chen", "name": "Chen Wu", "role": "Resharer"},
                    {"id": "dina", "name": "Dina Farouk", "role": "Resharer"},
                    {"id": "erik", "name": "Erik Novak", "role": "Resharer"},
                    {"id": "fatima", "name": "Fatima Diallo", "role": "Resharer"},
                    {"id": "gio", "name": "Gio Marino", "role": "Outer ring"},
                    {"id": "hana", "name": "Hana Petrova", "role": "Outer ring"},
                ],
                "edges": [
                    ["pulse", "anita", 3, "reshare"],
                    ["pulse", "ben", 3, "reshare"],
                    ["pulse", "chen", 3, "reshare"],
                    ["anita", "ben", 3, "reshare"],
                    ["anita", "chen", 3, "reshare"],
                    ["ben", "chen", 3, "reshare"],
                    ["dina", "erik", 3, "reshare"],
                    ["dina", "fatima", 3, "reshare"],
                    ["dina", "gio", 3, "reshare"],
                    ["dina", "hana", 3, "reshare"],
                    ["erik", "fatima", 3, "reshare"],
                    ["erik", "gio", 3, "reshare"],
                    ["erik", "hana", 3, "reshare"],
                    ["fatima", "gio", 3, "reshare"],
                    ["fatima", "hana", 3, "reshare"],
                    ["gio", "hana", 3, "reshare"],
                    ["chen", "dina", 1, "reshare"],
                    ["chen", "erik", 1, "reshare"],
                ],
                "comments": [
                    {"author": "chen", "lang": "en", "text": "The rumour reached the outer ring of accounts within a day."},
                    {"author": "dina", "lang": "es", "text": "Esto es una mierda de campaña. Te voy a matar si sigues publicando."},
                    {"author": "fatima", "lang": "en", "text": "Please share the primary source before we amplify this claim."},
                    {"author": "gio", "lang": "en", "text": "Go back to your country and stop posting in this health thread."},
                    {"author": "hana", "lang": "hi", "text": "तुम सब बेवकूफ हो."},
                    {"author": "pulse", "lang": "en", "text": "I'll kill you if you keep posting those corrections."},
                ],
            },
            {
                "id": "intervention",
                "label": "Intervention",
                "when": "Day 4",
                "note": "Fact-check flags cut the reshare paths. The outer community dissolves and the source cluster shrinks back to the original trio.",
                "nodes": [
                    {"id": "pulse", "name": "DailyPulse", "role": "Source account"},
                    {"id": "anita", "name": "Anita Roy", "role": "Early sharer"},
                    {"id": "ben", "name": "Ben Adler", "role": "Early sharer"},
                    {"id": "chen", "name": "Chen Wu", "role": "Resharer"},
                    {"id": "dina", "name": "Dina Farouk", "role": "Resharer"},
                    {"id": "erik", "name": "Erik Novak", "role": "Resharer"},
                    {"id": "fatima", "name": "Fatima Diallo", "role": "Resharer"},
                    {"id": "gio", "name": "Gio Marino", "role": "Outer ring"},
                    {"id": "hana", "name": "Hana Petrova", "role": "Outer ring"},
                ],
                "edges": [
                    ["pulse", "anita", 1, "reply"],
                    ["pulse", "ben", 1, "reply"],
                    ["anita", "ben", 1, "reply"],
                ],
                "comments": [
                    {"author": "fatima", "lang": "en", "text": "Fact-checking cut three reshare edges in the last snapshot. We should label uncertain claims instead of deleting the whole thread."},
                    {"author": "chen", "lang": "en", "text": "The intervention removed the edges out of the source account."},
                    {"author": "ben", "lang": "fr", "text": "Ferme ta gueule, connard."},
                    {"author": "anita", "lang": "en", "text": "I am leaving the thread. One toxic reply is enough to sour it."},
                ],
            },
        ],
    },
]
